### ISSUE TITLE
CSV data template files contain no data

### ISSUE THREAD

**Issue by eogmartins** [MOersted/Thermal-tolerances#2]
Hello, I was interested in trying out the codes associated with your Scientific Reports paper, but it seems that both the `static_input.csv` and `dynamic_input.csv` template data files have no data in them (only column headers). Would you be possible to please update them? Thanks.

**Comment by MOersted** [comment]
Dear Eduardo,

Thank you for taking an interest in our paper. 
The input files are meant to be empty as they simply serve as templates for your own data (making sure headers match the scripts). If you want to play around with the code, I have attached here example data used in the paper, and originally sourced from:
Jørgensen, L. B., Malte, H., & Overgaard, J. (2019). How to assess _Drosophila_ heat tolerance: unifying static and dynamic tolerance assays to predict heat distribution limits. Functional Ecology, 33(4), 629-642.

[dynamic_input.xlsx](https://github.com/user-attachments/files/16558775/dynamic_input.xlsx)
[static_input.xlsx](https://github.com/user-attachments/files/16558776/static_input.xlsx)

**Comment by MOersted** [comment]
I have closed the issue, please do not hesitate to contact me again if any further issues arise
Cheers,
Michael

**Comment by eogmartins** [comment]
Hello Michael,

Ah OK. Understood. Thanks so much for sending these example data!

Best,

Edu

______________________________
Eduardo Martins, PhD
Associate Professor
Dept. Ecosystem Science and Management
Faculty of Environment
University of Northern British Columbia
Phone: 250-960-5855
Email: ***@***.******@***.***>
Web: ffishlab.ca<https://www.ffishlab.ca/>

[signature_1658858300]
[signature_1058848824]


From: Michael Ørsted ***@***.***>
Date: Friday, August 9, 2024 at 02:02
To: MOersted/Thermal-tolerances ***@***.***>
Cc: Eduardo Martins ***@***.***>, Author ***@***.***>
Subject: Re: [MOersted/Thermal-tolerances] CSV data template files contain no data (Issue #2)
CAUTION: This email is not from UNBC. Avoid links and attachments. Don't buy gift cards.

Dear Eduardo,

Thank you for taking an interest in our paper.
The input files are meant to be empty as they simply serve as templates for your own data (making sure headers match the scripts). If you want to play around with the code, I have attached here example data used in the paper, and originally sourced from:
Jørgensen, L. B., Malte, H., & Overgaard, J. (2019). How to assess Drosophila heat tolerance: unifying static and dynamic tolerance assays to predict heat distribution limits. Functional Ecology, 33(4), 629-642.

dynamic_input.xlsx<https://github.com/user-attachments/files/16558775/dynamic_input.xlsx>
static_input.xlsx<https://github.com/user-attachments/files/16558776/static_input.xlsx>
